#!/usr/bin/env node
/**
 * Assembles the site pages: src/<page>.html templates + partials/ -> root <page>.html.
 *
 *   Templates contain full-line markers:
 *       <!-- @include header -->
 *       <!-- @include footer -->
 *   partials/header.html contains the slot:
 *       <!-- @nav -->
 *   which is filled with the page's nav fragment (or removed, leaving no
 *   blank line).
 *
 * Called by ./build.sh. No dependencies (plain node). Idempotent: a page is
 * rewritten only when its content actually changes. The generated root
 * files are committed — GH Pages has no build step.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

const header = read("partials/header.html");
const footer = read("partials/footer.html");

// [page, nav fragment for the header slot, or null for no nav]
const PAGES = [
    ["index.html", read("partials/nav-home.html")],
    ["privacy.html", null],
    ["terms.html", null],
    ["404.html", null],
];

const renderHeader = (nav) =>
    header.replace(
        /^[ \t]*<!-- @nav -->[ \t]*\r?\n/m,
        nav !== null ? nav.replace(/\n$/, "") + "\n" : "",
    );

let changed = 0;
for (const [page, nav] of PAGES) {
    let html = read("src/" + page);
    html = html.replace(/^[ \t]*<!-- @include header -->[ \t]*\r?\n/m, () => renderHeader(nav));
    html = html.replace(/^[ \t]*<!-- @include footer -->[ \t]*\r?\n/m, () => footer);
    if (html.includes("@include") || html.includes("@nav")) {
        console.error(`build-html: unexpanded marker left in ${page} — check src/${page} and partials/`);
        process.exit(1);
    }
    const out =
        `<!-- Generated by ./build.sh from src/${page} + partials/ — edit the sources, not this file. -->\n` +
        html;
    const file = join(root, page);
    if (readFileSync(file, "utf8") !== out) {
        writeFileSync(file, out);
        changed++;
    }
}
console.log(`Assembled ${PAGES.length} pages from src/ + partials/ (${changed} written)`);
